#!/bin/bash

# Prevent macOS from sleeping and terminating the session during setup.
# NOTE: We intentionally do NOT `exec caffeinate -i "$0" "$@"` here. When this
# script is run via `bash -c "$(curl -fsSL ...)"` (our own documented install
# command), $0 is just the literal string "bash", not a path to this script -
# so an exec-based re-launch replaces this process with a bare interactive
# bash shell instead of continuing setup. Running caffeinate in the
# background, pinned to our own PID, keeps the machine awake without
# depending on $0 at all, so it works the same via curl|bash, ./setup.sh, or
# bash setup.sh.
if [[ -z "$CAFFEINATED" ]]; then
    export CAFFEINATED=1
    caffeinate -i -w $$ &
fi

# ==============================================================================
# Script Name: Cisco AnyConnect Touch ID CLI Setup
# Description: Automated setup wizard for a secure, Touch ID-enabled, and 
#              TOTP-integrated Cisco AnyConnect VPN CLI on macOS.
# Author:      Piyal Ahmed
# Repository:  https://github.com/piyalahmed/cisco-autoconnect
# Version:     1.0.0
# Date:        May 2026
# ==============================================================================
# License:     MIT License
#
# Copyright (c) 2026 Piyal Ahmed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

# --- Styling & Colors ---
BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Uninstallation Logic (-r flag) ---
if [[ "$1" == "-r" ]]; then
    if [ -z "$2" ]; then
        echo -e "${RED}Error: Please specify the command name to remove. (e.g., ./setup.sh -r vpn)${NC}"
        exit 1
    fi
    
    CMD_TO_REMOVE="$2"
    BIN_PATH="/usr/local/bin/$CMD_TO_REMOVE"
    CREDS_PATH="$HOME/.${CMD_TO_REMOVE}-creds.gpg"
    
    echo -e "${BOLD}${YELLOW}Removal Process Initiated for '$CMD_TO_REMOVE'${NC}"
    
    if [ ! -f "$CREDS_PATH" ]; then
        echo -e "${RED}Error: Verification failed. No associated credential file found at '$CREDS_PATH'.${NC}"
        echo -e "${RED}To protect system files, this command will not be removed.${NC}"
        exit 1
    fi

    if [ -f "$BIN_PATH" ] && ! grep -q "Auto-generated by VPN CLI Setup" "$BIN_PATH" 2>/dev/null; then
        echo -e "${RED}Error: The command '$BIN_PATH' does not appear to be generated by this program.${NC}"
        echo -e "${RED}Aborting to protect system files.${NC}"
        exit 1
    fi
    
    echo -e "Removing encrypted credentials at $CREDS_PATH..."
    rm "$CREDS_PATH"
    echo -e "${GREEN}✓ Credentials removed.${NC}"
    
    if [ -f "$BIN_PATH" ]; then
        echo -e "Removing CLI tool at $BIN_PATH (requires sudo)..."
        sudo rm "$BIN_PATH"
        echo -e "${GREEN}✓ CLI tool removed.${NC}"
    fi
    
    echo -e "${BOLD}${GREEN}Cleanup complete for '$CMD_TO_REMOVE'.${NC}"
    exit 0
fi

# --- Standard Setup Flow ---
echo -e "${BOLD}${BLUE}====================================================${NC}"
echo -e "${BOLD}${BLUE}   Cisco AnyConnect CLI Auto-Connect Setup        ${NC}"
echo -e "${BOLD}${BLUE}====================================================${NC}\n"

# --- 0. Cisco Client Check ---
# This tool automates the Cisco VPN CLI - it doesn't install it. Check for it
# up front so a missing client fails fast with a clear message, instead of
# the whole wizard completing successfully and only failing later at `vpn -c`.
# Checks both the legacy AnyConnect path and the newer rebranded "Cisco
# Secure Client" path.
CISCO_VPN_CLI=""
for candidate in "/opt/cisco/anyconnect/bin/vpn" "/opt/cisco/secureclient/bin/vpn"; do
    if [ -x "$candidate" ]; then
        CISCO_VPN_CLI="$candidate"
        break
    fi
done

if [ -z "$CISCO_VPN_CLI" ]; then
    echo -e "${RED}Cisco AnyConnect / Cisco Secure Client CLI was not found at:${NC}"
    echo -e "  /opt/cisco/anyconnect/bin/vpn"
    echo -e "  /opt/cisco/secureclient/bin/vpn"
    echo -e "${RED}Install the Cisco AnyConnect / Cisco Secure Mobility Client from your organization first, then re-run this script.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Cisco VPN client found at $CISCO_VPN_CLI${NC}\n"

# --- 1. Biometric Preference ---
# Asked up front (before we install anything) so we only pull in
# pinentry-touchid when it's actually wanted, and fall back to plain
# password-based GPG encryption (pinentry-mac) otherwise.
echo -e "${BOLD}Biometric Security${NC}"
echo "Touch ID lets you approve VPN connections with your fingerprint instead of"
echo "typing your GPG passphrase every time."
read -p "Use Touch ID? (Y/n, recommended): " TOUCH_ID_CHOICE
TOUCH_ID_CHOICE=${TOUCH_ID_CHOICE:-y}
echo ""

# --- 2. Dependency Scan ---
# Scan first, based on the Touch ID choice above, then show the user exactly
# what's already present and what's missing, and ask ONE yes/no to install
# everything that's missing - no per-package prompts.
echo -e "${BOLD}Scanning dependencies...${NC}"

NEED_BREW=0
if ! command -v brew &> /dev/null; then
    NEED_BREW=1
fi

PRESENT_NAMES=()
MISSING_NAMES=()
MISSING_PACKAGES=()
MISSING_TAPS=()

check_dep() {
    local name=$1 package=$2 command_to_check=$3 tap=$4
    if command -v "$command_to_check" &> /dev/null; then
        PRESENT_NAMES+=("$name")
    else
        MISSING_NAMES+=("$name")
        MISSING_PACKAGES+=("$package")
        MISSING_TAPS+=("$tap")
    fi
}

check_dep "GnuPG" "gnupg" "gpg" ""
check_dep "OATH Toolkit" "oath-toolkit" "oathtool" ""
check_dep "pinentry-mac" "pinentry-mac" "pinentry-mac" ""
if [[ "$TOUCH_ID_CHOICE" =~ ^[Yy]$ ]]; then
    check_dep "pinentry-touchid" "pinentry-touchid" "pinentry-touchid" "jorgelbg/tap"
fi

if command -v python3 &> /dev/null; then
    PRESENT_NAMES+=("Python (python3)")
elif command -v python &> /dev/null; then
    PRESENT_NAMES+=("Python")
else
    MISSING_NAMES+=("Python")
    MISSING_PACKAGES+=("python")
    MISSING_TAPS+=("")
fi

echo ""
if [ ${#PRESENT_NAMES[@]} -gt 0 ]; then
    echo -e "${GREEN}Already installed:${NC}"
    for n in "${PRESENT_NAMES[@]}"; do echo -e "  ${GREEN}✓${NC} $n"; done
fi

if [ "$NEED_BREW" -eq 1 ] || [ ${#MISSING_NAMES[@]} -gt 0 ]; then
    echo -e "${YELLOW}Will be installed:${NC}"
    [ "$NEED_BREW" -eq 1 ] && echo -e "  ${YELLOW}•${NC} Homebrew (package manager)"
    for n in "${MISSING_NAMES[@]}"; do echo -e "  ${YELLOW}•${NC} $n"; done
    echo ""
    read -p "Proceed with installing the above? (Y/n): " INSTALL_CONFIRM
    INSTALL_CONFIRM=${INSTALL_CONFIRM:-y}
    if [[ ! "$INSTALL_CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${RED}Cannot proceed without these dependencies. Exiting.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}✓ All dependencies already satisfied.${NC}"
fi
echo ""

# --- Dependency Install ---
if [ "$NEED_BREW" -eq 1 ]; then
    echo -e "${YELLOW}Installing Homebrew (its installer will prompt for confirmation/sudo itself)...${NC}"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    if [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi

    if ! command -v brew &> /dev/null; then
        echo -e "${RED}Homebrew installation did not complete. Please install it manually and re-run this script.${NC}"
        exit 1
    fi
fi

BREW_PREFIX=$(brew --prefix)
OATHTOOL_PATH="$BREW_PREFIX/bin/oathtool"

for i in "${!MISSING_PACKAGES[@]}"; do
    echo -e "${YELLOW}Installing ${MISSING_NAMES[$i]}...${NC}"
    [ -n "${MISSING_TAPS[$i]}" ] && brew tap "${MISSING_TAPS[$i]}"
    brew install "${MISSING_PACKAGES[$i]}"
done

# Verify the mandatory tools landed (pinentry-touchid is allowed to fail here;
# step 7 below falls back to the password prompt if it's still missing).
for cmd in gpg oathtool pinentry-mac; do
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "${RED}Error: '$cmd' is still missing after installation. Exiting.${NC}"
        exit 1
    fi
done

if command -v python3 &> /dev/null; then
    PYTHON_CMD="python3"
elif command -v python &> /dev/null; then
    PYTHON_CMD="python"
else
    echo -e "${RED}Error: Python is still missing after installation. Exiting.${NC}"
    exit 1
fi

echo ""

# --- 3. GPG Key Check ---
echo -e "${BOLD}Configuring Encryption...${NC}"
while ! gpg --list-secret-keys 2>/dev/null | grep -q "^sec"; do
    echo -e "${YELLOW}No GPG secret key found.${NC}"
    echo "You need to set up GPG before continuing. Run the following command in a new terminal window:"
    echo -e "  ${BOLD}gpg --full-generate-key${NC}"
    read -p "Press Enter once you have completed the GPG setup to continue..."
done
echo -e "${GREEN}✓ GPG key found.${NC}"

echo -e "Please enter the ${BOLD}Email Address${NC} associated with your GPG key."
read -p "GPG Email: " GPG_EMAIL

GPG_AGENT_CONF="$HOME/.gnupg/gpg-agent.conf"
mkdir -p "$HOME/.gnupg"
echo "pinentry-program $BREW_PREFIX/bin/pinentry-mac" > "$GPG_AGENT_CONF"
gpgconf --kill gpg-agent

echo ""

# --- 4. Configuration & Credentials ---
echo -e "${BOLD}Configuring VPN Profile...${NC}"
read -p "Desired Terminal Command Name (e.g., vpn): " CMD_NAME
CMD_NAME=${CMD_NAME:-vpn}

read -p "VPN Server Address (e.g., vpn.company.com): " VPN_SERVER
read -p "VPN Username: " VPN_USER

echo -e "\n${BOLD}Secure Credential Entry${NC}"
echo "These will be encrypted via GPG. The plaintext will not be saved."
read -s -p "VPN Password: " VPN_PASS
echo ""

# --- TOTP Input Loop ---
while true; do
    echo -e "\nPaste your TOTP Secret (You can paste the raw Base32 secret OR the long 'otpauth-migration://' link from Google Authenticator)"
    read -p "TOTP Input: " TOTP_INPUT 
    echo ""

    if [ -z "$TOTP_INPUT" ]; then
        echo -e "${RED}Input cannot be empty. Please try again.${NC}"
        continue
    fi

    # Remove trailing/leading spaces from copy/pasting
    TOTP_INPUT=$(echo "$TOTP_INPUT" | tr -d ' \t\n\r')
    TOTP_INPUT=$("$PYTHON_CMD" -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$TOTP_INPUT")

    if [[ "$TOTP_INPUT" == otpauth-migration://* ]]; then
        echo -e "${YELLOW}Google Authenticator export detected. Decoding in the background...${NC}"
        
        TMP_DIR=$(mktemp -d)
        cd "$TMP_DIR" || exit
        git clone --quiet https://github.com/brookst/otpauth_migrate.git
        cd otpauth_migrate || exit
        
        "$PYTHON_CMD" -m venv venv
        source venv/bin/activate
        pip install --quiet --disable-pip-version-check -r requirements.txt
        
        EXTRACTED_SECRET=$(python otpauth_migrate.py "$TOTP_INPUT" | grep -i "Secret code" | head -n 1 | sed 's/.*Secret code[[:space:]]*=[[:space:]]*//i')
        EXTRACTED_SECRET=$(echo "$EXTRACTED_SECRET" | tr -d ' \t\n\r"')
        
        deactivate
        cd - > /dev/null || exit
        rm -rf "$TMP_DIR"

        if [ -n "$EXTRACTED_SECRET" ]; then
            TOTP_SECRET="$EXTRACTED_SECRET"
            echo -e "${GREEN}✓ Secret extracted successfully: ${BOLD}$TOTP_SECRET${NC}"
        else
            echo -e "${RED}Failed to decode the link. Please try again or provide the raw Base32 secret.${NC}"
            continue
        fi
    else
        TOTP_SECRET=$(echo "$TOTP_INPUT" | tr -d ' \t\n\r')
    fi

    # --- 3.5 TOTP Verification ---
    echo -e "\n${BOLD}Verifying OTP Secret...${NC}"
    
    # Pre-check to ensure the string is valid before asking the user to look at their phone
    PRE_CHECK_TOKEN=$("$OATHTOOL_PATH" --totp -b "$TOTP_SECRET" 2>/dev/null)

    if [ -z "$PRE_CHECK_TOKEN" ]; then
        echo -e "${RED}Error: The provided secret is invalid. oathtool could not generate a code.${NC}"
        echo -e "${YELLOW}Please double check your input and try again.${NC}"
        continue
    fi

    echo -e "${YELLOW}Open your Authenticator app and compare it against the live code below.${NC}"
    echo -e "${YELLOW}Press [Enter] once you're ready to confirm.${NC}\n"

    # Live countdown display: regenerate the token every second and redraw in
    # place, so the code on screen tracks the real TOTP window instead of
    # being a single snapshot that can go stale while the user looks away.
    while true; do
        REMAINING=$(( 30 - ($(date +%s) % 30) ))
        LIVE_TOKEN=$("$OATHTOOL_PATH" --totp -b "$TOTP_SECRET" 2>/dev/null)
        printf "\r  ${BOLD}${GREEN}%s${NC}   ${YELLOW}(refreshes in %2ds)${NC}   " "$LIVE_TOKEN" "$REMAINING"
        if read -t 1 -n 1 -s _; then
            break
        fi
    done
    printf "\n\n"

    read -p "Does that match the code currently shown in your Authenticator app? (y/n): " OTP_CONFIRM

    if [[ "$OTP_CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✓ OTP verification successful! Proceeding with encryption...${NC}\n"
        break
    else
        echo -e "${RED}Code mismatch. Let's try entering the secret again.${NC}"
    fi
done

# --- 5. Encrypt Credentials ---
CREDS_FILE="$HOME/.${CMD_NAME}-creds.gpg"

cat <<EOF > /tmp/vpn-creds-tmp.txt
$VPN_PASS
$TOTP_SECRET
EOF

gpg --yes --quiet --encrypt --recipient "$GPG_EMAIL" --output "$CREDS_FILE" /tmp/vpn-creds-tmp.txt
rm -P /tmp/vpn-creds-tmp.txt 2>/dev/null || rm /tmp/vpn-creds-tmp.txt

echo -e "${GREEN}✓ Credentials encrypted and saved to $CREDS_FILE${NC}\n"

# --- 6. Initial Keychain Handshake ---
echo -e "${BOLD}Initial Keychain Setup${NC}"
echo "We need to save your GPG password to the macOS Keychain so the automation works."
echo -e "${YELLOW}A standard Mac password prompt will appear in a moment.${NC}"
echo -e "${RED}CRITICAL: You MUST check the box that says 'Save in Keychain' before hitting OK!${NC}"
read -p "Press Enter when you are ready..."

gpg --decrypt --quiet "$CREDS_FILE" > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Verification successful.${NC}\n"
else
    echo -e "${RED}Decryption failed. You may have typed the wrong password or closed the prompt.${NC}"
    exit 1
fi

# --- 7. Touch ID Activation ---
# (Preference was already collected in step 1, before dependencies were installed.)
echo -e "${BOLD}Biometric Security${NC}"

if [[ "$TOUCH_ID_CHOICE" =~ ^[Yy]$ ]]; then
    if [ ! -x "$BREW_PREFIX/bin/pinentry-touchid" ]; then
        echo -e "${RED}Error: pinentry-touchid is not installed at $BREW_PREFIX/bin/pinentry-touchid.${NC}"
        echo -e "${RED}Keeping the standard pinentry-mac prompt instead.${NC}\n"
    else
        echo "pinentry-program $BREW_PREFIX/bin/pinentry-touchid" > "$GPG_AGENT_CONF"
        gpgconf --kill gpg-agent
        echo -e "${GREEN}✓ Touch ID enabled.${NC}\n"
    fi
else
    echo -e "${GREEN}✓ Standard password prompt maintained.${NC}\n"
fi

# --- 8. Generate the CLI Tool ---
echo -e "${BOLD}Generating CLI Tool...${NC}"
TARGET_BIN="/usr/local/bin/$CMD_NAME"

cat <<EOF > "/tmp/$CMD_NAME"
#!/bin/bash

# Auto-generated by VPN CLI Setup
USERNAME="$VPN_USER"
VPN_SERVER="$VPN_SERVER"
VPN_CLI="$CISCO_VPN_CLI"
OATHTOOL="$OATHTOOL_PATH"
CREDS_FILE="$CREDS_FILE"
GPG_EMAIL="$GPG_EMAIL"

connect_vpn() {
    CURRENT_STATE=\$("\$VPN_CLI" state | grep ">> state:" | tail -n 1 | sed 's/.*state: //')
    if [ "\$CURRENT_STATE" = "Connected" ]; then
        echo "Already connected to \$VPN_SERVER."
        exit 0
    fi

    DECRYPTED_DATA=\$(gpg --decrypt --quiet "\$CREDS_FILE" 2>/dev/null)
    PASSWORD=\$(echo "\$DECRYPTED_DATA" | sed -n '1p')
    TOTP_SECRET=\$(echo "\$DECRYPTED_DATA" | sed -n '2p')

    if [ -z "\$PASSWORD" ] || [ -z "\$TOTP_SECRET" ]; then
        echo "Error: Failed to decrypt credentials. Did you cancel the prompt?"
        exit 1
    fi

    TOKEN=\$("\$OATHTOOL" --totp -b "\$TOTP_SECRET")
    unset TOTP_SECRET DECRYPTED_DATA 
    
    echo "Connecting to \$VPN_SERVER..."
    
    OUTPUT=\$(printf "\$USERNAME\n\$TOKEN\n\$PASSWORD\ny\n" | "\$VPN_CLI" -s connect "\$VPN_SERVER" 2>&1)
    
    if echo "\$OUTPUT" | grep -q ">> state: Connected"; then
        # Use ANSI escape codes to jump up 2 lines and clear Cisco's terminal leakage
        printf "\033[2A\033[J"
        echo "Connected successfully."
    else
        echo "Connection failed. Debug log:"
        echo "\$OUTPUT"
    fi
    unset PASSWORD TOKEN
}

disconnect_vpn() {
    echo "Disconnecting..."
    "\$VPN_CLI" disconnect > /dev/null 2>&1
    echo "Disconnected."
}

status_vpn() {
    STATE=\$("\$VPN_CLI" state | grep ">> state:" | tail -n 1 | sed 's/.*state: //')
    if [ "\$STATE" = "Connected" ]; then
        echo "Connected"
    elif [ "\$STATE" = "Disconnected" ]; then
        echo "Disconnected"
    else
        echo "Status unknown: \$STATE"
    fi
}

update_credentials() {
    echo "Updating VPN password for \$USERNAME..."
    read -s -p "Enter new VPN Password: " NEW_PASSWORD
    echo ""

    if [ -z "\$NEW_PASSWORD" ]; then
        echo "Error: Password cannot be empty."
        exit 1
    fi

    echo "Authenticating to access existing TOTP secret..."
    DECRYPTED_DATA=\$(gpg --decrypt --quiet "\$CREDS_FILE" 2>/dev/null)
    TOTP_SECRET=\$(echo "\$DECRYPTED_DATA" | sed -n '2p')

    if [ -z "\$TOTP_SECRET" ]; then
        echo "Error: Failed to retrieve existing TOTP secret. Update aborted."
        exit 1
    fi

    printf "%s\n%s\n" "\$NEW_PASSWORD" "\$TOTP_SECRET" > /tmp/vpn-creds-update.txt
    gpg --yes --quiet --encrypt --recipient "\$GPG_EMAIL" --output "\$CREDS_FILE" /tmp/vpn-creds-update.txt
    rm -P /tmp/vpn-creds-update.txt 2>/dev/null || rm /tmp/vpn-creds-update.txt

    echo "✓ Password successfully updated!"
    unset NEW_PASSWORD TOTP_SECRET DECRYPTED_DATA
}

show_help() {
    echo "Usage: $CMD_NAME [option]"
    echo "Options:"
    echo "  -c    Connect to the VPN"
    echo "  -d    Disconnect from the VPN"
    echo "  -s    Check VPN status"
    echo "  -u    Update VPN password"
    echo "  -h    Show this help message"
}

if [ "\$1" != "-h" ] && [ ! -x "\$VPN_CLI" ]; then
    echo "Error: Cisco VPN client not found at \$VPN_CLI."
    echo "It may have been uninstalled or moved. Re-run setup.sh to detect its new location."
    exit 1
fi

case "\$1" in
    -c) connect_vpn ;;
    -d) disconnect_vpn ;;
    -s) status_vpn ;;
    -u) update_credentials ;;
    -h) show_help ;;
    *)  
        echo "Invalid or missing option."
        show_help
        exit 1
        ;;
esac
EOF

chmod +x "/tmp/$CMD_NAME"

echo -e "We need administrator privileges to place the command in ${BOLD}/usr/local/bin${NC}."
sudo mv "/tmp/$CMD_NAME" "$TARGET_BIN"

echo -e "\n${BOLD}${GREEN}====================================================${NC}"
echo -e "${BOLD}${GREEN}  Setup Complete!                                   ${NC}"
echo -e "${BOLD}${GREEN}====================================================${NC}"
echo -e "Try it out by typing: ${BOLD}$CMD_NAME -c${NC} or ${BOLD}$CMD_NAME -h${NC} for help\n"