#!/bin/bash

# Prevent macOS from sleeping and terminating the session during setup
if [[ -z "$CAFFEINATED" ]]; then
    export CAFFEINATED=1
    exec caffeinate -i "$0" "$@"
fi

# ==============================================================================
# Script Name: Cisco AnyConnect Touch ID CLI Setup
# Description: Automated setup wizard for a secure, Touch ID-enabled, and 
#              TOTP-integrated Cisco AnyConnect VPN CLI on macOS.
# Author:      Piyal Ahmed
# Repository:  https://github.com/piyalahmed/cisco-autoconnect
# Version:     1.0.0
# Date:        May 2026
# ==============================================================================
# License:     MIT License
#
# Copyright (c) 2026 Piyal Ahmed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================

# --- Styling & Colors ---
BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Uninstallation Logic (-r flag) ---
if [[ "$1" == "-r" ]]; then
    if [ -z "$2" ]; then
        echo -e "${RED}Error: Please specify the command name to remove. (e.g., ./setup.sh -r vpn)${NC}"
        exit 1
    fi
    
    CMD_TO_REMOVE="$2"
    BIN_PATH="/usr/local/bin/$CMD_TO_REMOVE"
    CREDS_PATH="$HOME/.${CMD_TO_REMOVE}-creds.gpg"
    
    echo -e "${BOLD}${YELLOW}Removal Process Initiated for '$CMD_TO_REMOVE'${NC}"
    
    if [ ! -f "$CREDS_PATH" ]; then
        echo -e "${RED}Error: Verification failed. No associated credential file found at '$CREDS_PATH'.${NC}"
        echo -e "${RED}To protect system files, this command will not be removed.${NC}"
        exit 1
    fi

    if [ -f "$BIN_PATH" ] && ! grep -q "Auto-generated by VPN CLI Setup" "$BIN_PATH" 2>/dev/null; then
        echo -e "${RED}Error: The command '$BIN_PATH' does not appear to be generated by this program.${NC}"
        echo -e "${RED}Aborting to protect system files.${NC}"
        exit 1
    fi
    
    echo -e "Removing encrypted credentials at $CREDS_PATH..."
    rm "$CREDS_PATH"
    echo -e "${GREEN}✓ Credentials removed.${NC}"
    
    if [ -f "$BIN_PATH" ]; then
        echo -e "Removing CLI tool at $BIN_PATH (requires sudo)..."
        sudo rm "$BIN_PATH"
        echo -e "${GREEN}✓ CLI tool removed.${NC}"
    fi
    
    echo -e "${BOLD}${GREEN}Cleanup complete for '$CMD_TO_REMOVE'.${NC}"
    exit 0
fi

# --- Standard Setup Flow ---
echo -e "${BOLD}${BLUE}====================================================${NC}"
echo -e "${BOLD}${BLUE}   Cisco AnyConnect CLI Auto-Connect Setup        ${NC}"
echo -e "${BOLD}${BLUE}====================================================${NC}\n"

# --- 1. Dependency Checks ---
echo -e "${BOLD}Checking dependencies...${NC}"

if ! command -v brew &> /dev/null; then
    echo -e "${RED}Homebrew is not installed. Please install Homebrew first and run this script again.${NC}"
    exit 1
fi

BREW_PREFIX=$(brew --prefix)
OATHTOOL_PATH="$BREW_PREFIX/bin/oathtool"

install_dependency() {
    local package=$1
    local command_to_check=$2
    local tap=$3

    if ! command -v "$command_to_check" &> /dev/null; then
        echo -e "${YELLOW}$package is missing.${NC}"
        read -p "Would you like to install it via Homebrew? (y/n): " choice
        case "$choice" in 
            y|Y ) 
                if [ -n "$tap" ]; then brew tap "$tap" >/dev/null 2>&1; fi
                brew install "$package"
                ;;
            * ) 
                echo -e "${RED}Cannot proceed without $package. Exiting.${NC}"
                exit 1
                ;;
        esac
    else
        echo -e "${GREEN}✓ $package is installed.${NC}"
    fi
}

# --- Dynamic Python Checker ---
check_python() {
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
        echo -e "${GREEN}✓ Python is installed ($PYTHON_CMD).${NC}"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
        echo -e "${GREEN}✓ Python is installed ($PYTHON_CMD).${NC}"
    else
        echo -e "${YELLOW}Python is missing. It is required to decode Google Authenticator links.${NC}"
        read -p "Would you like to install it via Homebrew? (y/n): " choice
        case "$choice" in 
            y|Y ) 
                brew install python
                PYTHON_CMD="python3"
                ;;
            * ) 
                echo -e "${RED}Cannot proceed without Python. Exiting.${NC}"
                exit 1
                ;;
        esac
    fi
}

install_dependency "gnupg" "gpg"
install_dependency "oath-toolkit" "oathtool"
install_dependency "pinentry-mac" "pinentry-mac"
install_dependency "pinentry-touchid" "pinentry-touchid" "jorgelbg/tap"
check_python

echo ""

# --- 2. GPG Key Check ---
echo -e "${BOLD}Configuring Encryption...${NC}"
while ! gpg --list-secret-keys 2>/dev/null | grep -q "^sec"; do
    echo -e "${YELLOW}No GPG secret key found.${NC}"
    echo "You need to set up GPG before continuing. Run the following command in a new terminal window:"
    echo -e "  ${BOLD}gpg --full-generate-key${NC}"
    read -p "Press Enter once you have completed the GPG setup to continue..."
done
echo -e "${GREEN}✓ GPG key found.${NC}"

echo -e "Please enter the ${BOLD}Email Address${NC} associated with your GPG key."
read -p "GPG Email: " GPG_EMAIL

GPG_AGENT_CONF="$HOME/.gnupg/gpg-agent.conf"
mkdir -p "$HOME/.gnupg"
echo "pinentry-program $BREW_PREFIX/bin/pinentry-mac" > "$GPG_AGENT_CONF"
gpgconf --kill gpg-agent

echo ""

# --- 3. Configuration & Credentials ---
echo -e "${BOLD}Configuring VPN Profile...${NC}"
read -p "Desired Terminal Command Name (e.g., vpn): " CMD_NAME
CMD_NAME=${CMD_NAME:-vpn}

read -p "VPN Server Address (e.g., vpn.company.com): " VPN_SERVER
read -p "VPN Username: " VPN_USER

echo -e "\n${BOLD}Secure Credential Entry${NC}"
echo "These will be encrypted via GPG. The plaintext will not be saved."
read -s -p "VPN Password: " VPN_PASS
echo ""

# --- TOTP Input Loop ---
while true; do
    echo -e "\nPaste your TOTP Secret (You can paste the raw Base32 secret OR the long 'otpauth-migration://' link from Google Authenticator)"
    read -p "TOTP Input: " TOTP_INPUT 
    echo ""

    if [ -z "$TOTP_INPUT" ]; then
        echo -e "${RED}Input cannot be empty. Please try again.${NC}"
        continue
    fi

    # Remove trailing/leading spaces from copy/pasting
    TOTP_INPUT=$(echo "$TOTP_INPUT" | tr -d ' \t\n\r')
    TOTP_INPUT=$("$PYTHON_CMD" -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$TOTP_INPUT")

    if [[ "$TOTP_INPUT" == otpauth-migration://* ]]; then
        echo -e "${YELLOW}Google Authenticator export detected. Decoding in the background...${NC}"
        
        TMP_DIR=$(mktemp -d)
        cd "$TMP_DIR" || exit
        git clone --quiet https://github.com/brookst/otpauth_migrate.git
        cd otpauth_migrate || exit
        
        "$PYTHON_CMD" -m venv venv
        source venv/bin/activate
        pip install --quiet --disable-pip-version-check -r requirements.txt
        
        EXTRACTED_SECRET=$(python otpauth_migrate.py "$TOTP_INPUT" | grep -i "Secret code" | head -n 1 | sed 's/.*Secret code[[:space:]]*=[[:space:]]*//i')
        EXTRACTED_SECRET=$(echo "$EXTRACTED_SECRET" | tr -d ' \t\n\r"')
        
        deactivate
        cd - > /dev/null || exit
        rm -rf "$TMP_DIR"

        if [ -n "$EXTRACTED_SECRET" ]; then
            TOTP_SECRET="$EXTRACTED_SECRET"
            echo -e "${GREEN}✓ Secret extracted successfully: ${BOLD}$TOTP_SECRET${NC}"
        else
            echo -e "${RED}Failed to decode the link. Please try again or provide the raw Base32 secret.${NC}"
            continue
        fi
    else
        TOTP_SECRET=$(echo "$TOTP_INPUT" | tr -d ' \t\n\r')
    fi

    # --- 3.5 TOTP Verification ---
    echo -e "\n${BOLD}Verifying OTP Secret...${NC}"
    
    # Pre-check to ensure the string is valid before asking the user to look at their phone
    PRE_CHECK_TOKEN=$("$OATHTOOL_PATH" --totp -b "$TOTP_SECRET" 2>/dev/null)

    if [ -z "$PRE_CHECK_TOKEN" ]; then
        echo -e "${RED}Error: The provided secret is invalid. oathtool could not generate a code.${NC}"
        echo -e "${YELLOW}Please double check your input and try again.${NC}"
        continue
    fi

    echo -e "${YELLOW}Please open your Authenticator app and find the current 6-digit code for this VPN.${NC}"
    read -p "Press [Enter] when you are looking at it..."

    # Re-generate the token instantly so it doesn't expire during the wait
    TEST_TOKEN=$("$OATHTOOL_PATH" --totp -b "$TOTP_SECRET" 2>/dev/null)

    echo -e "Live 6-digit code generated: ${BOLD}${GREEN}$TEST_TOKEN${NC}"
    echo -e "${YELLOW}(Note: Codes change every 30 seconds. If it just changed on your phone, wait a moment to see if they match.)${NC}"
    read -p "Does this match the code currently shown in your Authenticator app? (y/n): " OTP_CONFIRM

    if [[ "$OTP_CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✓ OTP verification successful! Proceeding with encryption...${NC}\n"
        break
    else
        echo -e "${RED}Code mismatch. Let's try entering the secret again.${NC}"
    fi
done

# --- 4. Encrypt Credentials ---
CREDS_FILE="$HOME/.${CMD_NAME}-creds.gpg"

cat <<EOF > /tmp/vpn-creds-tmp.txt
$VPN_PASS
$TOTP_SECRET
EOF

gpg --yes --quiet --encrypt --recipient "$GPG_EMAIL" --output "$CREDS_FILE" /tmp/vpn-creds-tmp.txt
rm -P /tmp/vpn-creds-tmp.txt 2>/dev/null || rm /tmp/vpn-creds-tmp.txt

echo -e "${GREEN}✓ Credentials encrypted and saved to $CREDS_FILE${NC}\n"

# --- 5. Initial Keychain Handshake ---
echo -e "${BOLD}Initial Keychain Setup${NC}"
echo "We need to save your GPG password to the macOS Keychain so the automation works."
echo -e "${YELLOW}A standard Mac password prompt will appear in a moment.${NC}"
echo -e "${RED}CRITICAL: You MUST check the box that says 'Save in Keychain' before hitting OK!${NC}"
read -p "Press Enter when you are ready..."

gpg --decrypt --quiet "$CREDS_FILE" > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Verification successful.${NC}\n"
else
    echo -e "${RED}Decryption failed. You may have typed the wrong password or closed the prompt.${NC}"
    exit 1
fi

# --- 6. Touch ID Setup ---
echo -e "${BOLD}Biometric Security${NC}"
read -p "Do you want to require Touch ID to connect to the VPN? (y/n): " TOUCH_ID_CHOICE

if [[ "$TOUCH_ID_CHOICE" =~ ^[Yy]$ ]]; then
    echo "pinentry-program $BREW_PREFIX/bin/pinentry-touchid" > "$GPG_AGENT_CONF"
    gpgconf --kill gpg-agent
    echo -e "${GREEN}✓ Touch ID enabled.${NC}\n"
else
    echo -e "${GREEN}✓ Standard password prompt maintained.${NC}\n"
fi

# --- 7. Generate the CLI Tool ---
echo -e "${BOLD}Generating CLI Tool...${NC}"
TARGET_BIN="/usr/local/bin/$CMD_NAME"

cat <<EOF > "/tmp/$CMD_NAME"
#!/bin/bash

# Auto-generated by VPN CLI Setup
USERNAME="$VPN_USER"
VPN_SERVER="$VPN_SERVER"
VPN_CLI="/opt/cisco/anyconnect/bin/vpn"
OATHTOOL="$OATHTOOL_PATH"
CREDS_FILE="$CREDS_FILE"
GPG_EMAIL="$GPG_EMAIL"

connect_vpn() {
    CURRENT_STATE=\$("\$VPN_CLI" state | grep ">> state:" | tail -n 1 | sed 's/.*state: //')
    if [ "\$CURRENT_STATE" = "Connected" ]; then
        echo "Already connected to \$VPN_SERVER."
        exit 0
    fi

    DECRYPTED_DATA=\$(gpg --decrypt --quiet "\$CREDS_FILE" 2>/dev/null)
    PASSWORD=\$(echo "\$DECRYPTED_DATA" | sed -n '1p')
    TOTP_SECRET=\$(echo "\$DECRYPTED_DATA" | sed -n '2p')

    if [ -z "\$PASSWORD" ] || [ -z "\$TOTP_SECRET" ]; then
        echo "Error: Failed to decrypt credentials. Did you cancel the prompt?"
        exit 1
    fi

    TOKEN=\$("\$OATHTOOL" --totp -b "\$TOTP_SECRET")
    unset TOTP_SECRET DECRYPTED_DATA 
    
    echo "Connecting to \$VPN_SERVER..."
    
    OUTPUT=\$(printf "\$USERNAME\n\$TOKEN\n\$PASSWORD\ny\n" | "\$VPN_CLI" -s connect "\$VPN_SERVER" 2>&1)
    
    if echo "\$OUTPUT" | grep -q ">> state: Connected"; then
        # Use ANSI escape codes to jump up 2 lines and clear Cisco's terminal leakage
        printf "\033[2A\033[J"
        echo "Connected successfully."
    else
        echo "Connection failed. Debug log:"
        echo "\$OUTPUT"
    fi
    unset PASSWORD TOKEN
}

disconnect_vpn() {
    echo "Disconnecting..."
    "\$VPN_CLI" disconnect > /dev/null 2>&1
    echo "Disconnected."
}

status_vpn() {
    STATE=\$("\$VPN_CLI" state | grep ">> state:" | tail -n 1 | sed 's/.*state: //')
    if [ "\$STATE" = "Connected" ]; then
        echo "Connected"
    elif [ "\$STATE" = "Disconnected" ]; then
        echo "Disconnected"
    else
        echo "Status unknown: \$STATE"
    fi
}

update_credentials() {
    echo "Updating VPN password for \$USERNAME..."
    read -s -p "Enter new VPN Password: " NEW_PASSWORD
    echo ""

    if [ -z "\$NEW_PASSWORD" ]; then
        echo "Error: Password cannot be empty."
        exit 1
    fi

    echo "Authenticating to access existing TOTP secret..."
    DECRYPTED_DATA=\$(gpg --decrypt --quiet "\$CREDS_FILE" 2>/dev/null)
    TOTP_SECRET=\$(echo "\$DECRYPTED_DATA" | sed -n '2p')

    if [ -z "\$TOTP_SECRET" ]; then
        echo "Error: Failed to retrieve existing TOTP secret. Update aborted."
        exit 1
    fi

    printf "%s\n%s\n" "\$NEW_PASSWORD" "\$TOTP_SECRET" > /tmp/vpn-creds-update.txt
    gpg --yes --quiet --encrypt --recipient "\$GPG_EMAIL" --output "\$CREDS_FILE" /tmp/vpn-creds-update.txt
    rm -P /tmp/vpn-creds-update.txt 2>/dev/null || rm /tmp/vpn-creds-update.txt

    echo "✓ Password successfully updated!"
    unset NEW_PASSWORD TOTP_SECRET DECRYPTED_DATA
}

show_help() {
    echo "Usage: $CMD_NAME [option]"
    echo "Options:"
    echo "  -c    Connect to the VPN"
    echo "  -d    Disconnect from the VPN"
    echo "  -s    Check VPN status"
    echo "  -u    Update VPN password"
    echo "  -h    Show this help message"
}

case "\$1" in
    -c) connect_vpn ;;
    -d) disconnect_vpn ;;
    -s) status_vpn ;;
    -u) update_credentials ;;
    -h) show_help ;;
    *)  
        echo "Invalid or missing option."
        show_help
        exit 1
        ;;
esac
EOF

chmod +x "/tmp/$CMD_NAME"

echo -e "We need administrator privileges to place the command in ${BOLD}/usr/local/bin${NC}."
sudo mv "/tmp/$CMD_NAME" "$TARGET_BIN"

echo -e "\n${BOLD}${GREEN}====================================================${NC}"
echo -e "${BOLD}${GREEN}  Setup Complete!                                   ${NC}"
echo -e "${BOLD}${GREEN}====================================================${NC}"
echo -e "Try it out by typing: ${BOLD}$CMD_NAME -c${NC} or ${BOLD}$CMD_NAME -h${NC} for help\n"